Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2019-10, with the labels that each got.

#62 govuk frontend updated to latest version: 3.0.0
  assets/js/main.js
  assets/scss/main.scss
  package.json
  steps/petitioner/progress-bar/PetitionerProgressBar.content.json
  steps/petitioner/progress-bar/sections/DivorceAwaiting.html
  steps/petitioner/progress-bar/sections/DivorceGranted.html
  steps/petitioner/progress-bar/sections/DivorceRequested.html
  steps/respondent/progress-bar/RespondentProgressBar.content.json
  steps/respondent/progress-bar/sections/DivorceGranted.html
  steps/respondent/progress-bar/sections/DivorceRequested.html
  yarn.lock
Labels: ns:div-da-pr-62

#80 Webchats - add live environment variables
  infrastructure/prod.tfvars
Labels: ns:div-da-pr-80

#81 enable webchat (test for prod)
  infrastructure/variables.tf
Labels: ns:div-da-pr-81

#82 Revert "enable webchat (test for prod)"
  infrastructure/variables.tf
Labels: ns:div-da-pr-82

#83 DIV-5914 - Use the correct opening hours for the website messages
  common/content.json
Labels: ns:div-da-pr-83

#86 Prepare for AKS migration
  .editorconfig
  charts/div-da/Chart.yaml
  charts/div-da/requirements.yaml
  charts/div-da/values.aat.template.yaml
  charts/div-da/values.preview.template.yaml
  charts/div-da/values.yaml
  config/custom-environment-variables.yml
  config/default.yml
  config/production.yml
  helpers/setupSecretsHelper.js
  infrastructure/.gitignore
  infrastructure/main.tf
  infrastructure/variables.tf
  middleware/healthcheck.js
  package.json
  services/app-insights.js
  services/rateLimiter.js
  test/unit/services/app-insights.test.js
  yarn.lock
Labels: ns:div-da-pr-86

#84 DIV-5756 - Enable webchat on live environment
  charts/div-da/values.yaml
  config/default.yml
  infrastructure/variables.tf
Labels: ns:div-da-pr-84

#87 Enable chart publishing and fix typo
  Jenkinsfile_CNP
  helpers/setupSecretsHelper.js
Labels: ns:div-da-pr-87

#88 Change base image to alpine
  Dockerfile
  acb.tpl.yaml
  docker-compose.yaml
  package.json
  yarn.lock
Labels: ns:div-da-pr-88

#89 Removed deprecated & unused NSP dependency and added resolution
  package.json
  yarn.lock
Labels: ns:div-da-pr-89

#90 DIV-5608: Updated Smart Survey URL
  app.js
  infrastructure/variables.tf
Labels: ns:div-da-pr-90
