Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2019-07, with the labels that each got.

#13 Updated links under GovUK guidance
  steps/petitioner/progress-bar/ProgressBar.content.json
  steps/petitioner/progress-bar/ProgressBar.html
  test/unit/steps/petitioner/progressBar.test.js
  views/includes/sideMenuCourtDetails.html
  views/includes/sideMenuGuidanceLinks.html
Labels: ns:div-da-pr-13

#16 Changed divorce contact email address as per service owners request
  steps/petitioner/progress-bar/ProgressBar.content.json
Labels: ns:div-da-pr-16

#18 Replaced mistake with pet firstname being duplicated
  steps/petitioner/progress-bar/ProgressBar.html
Labels: ns:div-da-pr-18

#20 Fixed minor issues in content on progressBar page
  common/content.json
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/exit/Exit.content.json
  steps/petitioner/progress-bar/ProgressBar.content.json
  test/unit/resources/courtsList.json
  views/errors/error-content.json
Labels: ns:div-da-pr-20

#19 DIV 5041: Add DA Download documents to frontend
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petitioner/progress-bar/ProgressBar.content.json
  steps/petitioner/progress-bar/ProgressBar.html
  steps/petitioner/progress-bar/ProgressBar.step.js
  test/unit/steps/petitioner/progressBar.test.js
Labels: ns:div-da-pr-19

#12 DIV-4930 Applicant Apply For DA
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petitioner/apply-for-da/ApplyForDA.content.json
  steps/petitioner/apply-for-da/ApplyForDA.step.js
  steps/petitioner/apply-for-da/ApplyForDA.template.html
  steps/petitioner/progress-bar/ProgressBar.step.js
  test/unit/steps/done.test.js
  test/unit/steps/petitioner/applyForDA.test.js
  test/unit/steps/petitioner/progressBar.test.js
Labels: ns:div-da-pr-12

#21 DIV-5073: DA holding Page
  config/default.yml
  mocks/steps/modify-session/sections/caseState.html
  steps/petitioner/progress-bar/ProgressBar.content.json
  steps/petitioner/progress-bar/ProgressBar.html
  steps/petitioner/progress-bar/ProgressBar.step.js
  test/unit/steps/petitioner/progressBar.test.js
Labels: ns:div-da-pr-21

#24 Introduce middleware to clear errors not associated with the current …
  middleware/removeNonCurrentStepErrors.js
  steps/petitioner/apply-for-da/ApplyForDA.step.js
  steps/petitioner/progress-bar/ProgressBar.step.js
  test/unit/middleware/removeNonCurrentStepErrors.test.js
Labels: ns:div-da-pr-24

#26 Point Preview to Master Branch
  charts/div-da/values.preview.template.yaml
Labels: ns:div-da-pr-26

#38 Minor content fixes
  mocks/services/case-orchestration/submit-da/__/POST.mock
  steps/petitioner/apply-for-da/ApplyForDecreeAbsolute.content.json
  steps/petitioner/progress-bar/ProgressBar.content.json
  test/unit/steps/petitioner/applyForDecreeAbsolute.test.js
  yarn.lock
Labels: ns:div-da-pr-38

#31 DIV-5215: Showing updated progress bar page when user applies for a decree abso…
  mocks/services/case-orchestration/submit-da/__/POST.mock
  mocks/services/case-orchestration/submit-da/__/mock-case.json
  services/caseOrchestrationService.js
  steps/petitioner/apply-for-da/ApplyForDecreeAbsolute.step.js
  test/unit/steps/entry.test.js
  test/unit/steps/petitioner/applyForDecreeAbsolute.test.js
Labels: ns:div-da-pr-31

#28 DIV-5273: Final DA Landing Page
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petitioner/progress-bar/ProgressBar.content.json
  steps/petitioner/progress-bar/ProgressBar.html
  steps/petitioner/progress-bar/ProgressBar.step.js
  steps/petitioner/progress-bar/sections/DivorceAwaiting.html
  steps/petitioner/progress-bar/sections/DivorceGranted.html
  steps/petitioner/progress-bar/sections/DivorceRequested.html
  test/unit/services/googleAnalytics.test.js
  test/unit/steps/petitioner/progressBar.test.js
Labels: ns:div-da-pr-28

#32 DIV-5252: Redirect respondent to RFE if case is not DivorceGranted
  charts/div-da/values.aat.template.yaml
  charts/div-da/values.preview.template.yaml
  config/custom-environment-variables.yml
  config/default.yml
  helpers/caseOrchestrationHelper.js
  helpers/redirectToFrontendHelper.js
  infrastructure/main.tf
  services/caseOrchestrationService.js
  test/unit/helpers/caseOrchestrationHelper.test.js
  test/unit/helpers/redirectToFrontendHelper.test.js
Labels: ns:div-da-pr-32

#30 DIV-5183: Sign out link in the header
  views/includes/propositional_navigation.html
Labels: ns:div-da-pr-30

#45 Update to new docker image naming format
  Dockerfile
  acb.tpl.yaml
Labels: ns:div-da-pr-45

#29 DIV-5241: Update DA landing page for DivorceGranted state
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petitioner/progress-bar/ProgressBar.html
  steps/petitioner/progress-bar/ProgressBar.step.js
  steps/petitioner/progress-bar/stateTemplates.js
  test/unit/services/googleAnalytics.test.js
  test/unit/steps/petitioner/progressBar.test.js
  yarn.lock
Labels: ns:div-da-pr-29

#41 DIV-5324: Update download endpoint variable
  infrastructure/variables.tf
Labels: ns:div-da-pr-41

#42 Reverting unintentional unit test change
  test/unit/steps/petitioner/applyForDecreeAbsolute.test.js
Labels: ns:div-da-pr-42

#39 DIV-5186: Create basic functional tests
  .gitignore
  functional-output/Happy_Path.failed.png
  functional-output/Pages.failed.png
  package.json
  test/e2e/pages/common/idam.step.js
  test/functional/codecept.conf.js
  test/functional/codecept.smoke.conf.js
  test/functional/helpers/JSWait.js
  test/functional/helpers/SauceLabsReportingHelper.js
  test/functional/helpers/caseConfigHelper.js
  test/functional/helpers/caseHelper.js
  test/functional/helpers/elementExist.js
  test/functional/helpers/idamConfigHelper.js
  test/functional/helpers/idamHelper.js
  test/functional/helpers/urlHelper.js
  test/functional/pages/applyForDecreeAbsolute.js
  test/functional/pages/contactDivorceTeamError.js
  test/functional/pages/cookie.step.js
  test/functional/pages/done.step.js
  test/functional/pages/exit.step.js
  test/functional/pages/idam.step.js
  test/functional/pages/privacyPolicy.step.js
  test/functional/pages/progressBar.js
  test/functional/pages/steps.js
  test/functional/pages/termsAndCondiction.step.js
  test/functional/paths/pages.js
  test/functional/saucelabs.conf.js
  test/resources/basic-divorce-session.json
  test/resources/localhost-ssl/localhost-ca.crt
  test/resources/localhost-ssl/localhost.crt
  test/resources/localhost-ssl/localhost.key
  test/resources/sessionToCosMapping.json
  yarn.lock
Labels: ns:div-da-pr-39

#44 DIV-5314: Text change on continue with divorce page
  steps/petitioner/apply-for-da/ApplyForDecreeAbsolute.content.json
Labels: ns:div-da-pr-44

#43 DIV-5315: Text change on holding page
  steps/petitioner/progress-bar/ProgressBar.content.json
  test/unit/steps/petitioner/progressBar.test.js
Labels: ns:div-da-pr-43

#46 DIV-5312: Displaying DA-related dates on landing page
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petitioner/progress-bar/ProgressBar.content.json
  test/unit/steps/petitioner/progressBar.test.js
Labels: ns:div-da-pr-46

#47 DIV-5305: Upgrade DA to use the new GovUK frontend
  Jenkinsfile_CNP
  assets/js/main.js
  assets/js/showHideContent.js
  assets/scss/main.scss
  package.json
  steps/contact-divorce-team-error/ContactDivorceTeamError.html
  steps/cookies-policy/CookiesPolicy.content.json
  steps/cookies-policy/CookiesPolicy.html
  steps/done/Done.content.json
  steps/done/Done.html
  steps/exit/Exit.content.json
  steps/exit/Exit.html
  steps/petitioner/apply-for-da/ApplyForDecreeAbsolute.html
  steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.content.json
  steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.html
  steps/petitioner/progress-bar/ProgressBar.content.json
  steps/petitioner/progress-bar/ProgressBar.html
  steps/petitioner/progress-bar/sections/DivorceAwaiting.html
  steps/petitioner/progress-bar/sections/DivorceGranted.html
  steps/petitioner/progress-bar/sections/DivorceRequested.html
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/privacy-policy/PrivacyPolicy.html
  steps/terms-and-conditions/TermsAndConditions.content.json
  steps/terms-and-conditions/TermsAndConditions.html
  test/a11y/index.js
  test/unit/mock/steps/idamLogin.test.js
  test/unit/mock/steps/modifiySession.test.js
  test/unit/steps/contactDivorceTeamError.test.js
  test/unit/steps/done.test.js
  test/unit/steps/petitioner/applyForDecreeAbsolute.test.js
  test/unit/steps/petitioner/progressBar.test.js
  test/unit/views/filters/date.test.js
  test/w3cjs/index.js
  views/errors/content.html
  views/errors/error-content.json
  views/errors/footer.html
  views/errors/not-found-error.html
  views/errors/server-error.html
  views/filters/date.js
  views/includes/problem_with_this_page.html
  views/includes/sideMenuCourtDetails.html
  views/includes/sideMenuGuidanceLinks.html
  views/page.njk
  views/question.njk
  yarn.lock
Labels: ns:div-da-pr-47

#53 Added ability to login via mocks as respondent
  mocks/services/case-orchestration/retrieve-aos-case/GET.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-case-resp.json
  mocks/services/idam.js
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  test/functional/pages/idam.step.js
  test/unit/mock/services/idam.test.js
  test/unit/mock/steps/idamLogin.test.js
Labels: ns:div-da-pr-53

#55 Added resolution for assign-deep
  package.json
  yarn.lock
Labels: ns:div-da-pr-55

#56 Reintroduce Yarn Audit
  Jenkinsfile_CNP
Labels: ns:div-da-pr-56

#37 DIV-5170: Update sign out page to have dynamic dates
  steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.content.json
  test/unit/steps/petitioner/exitNoLongerWantsToProceed.test.js
Labels: ns:div-da-pr-37

#59 DIV-5524 - block paper journey
  .gitignore
  Jenkinsfile_CNP
  README.md
  charts/div-da/values.aat.template.yaml
  charts/div-da/values.preview.template.yaml
  config/custom-environment-variables.yml
  config/default.yml
  config/example-local-aat.yml
  helpers/caseOrchestrationHelper.js
  infrastructure/main.tf
  mocks/services/case-orchestration/amend-petition/__/PUT.mock
  package.json
  services/caseOrchestrationService.js
  test/e2e/codecept.conf.js
  test/e2e/codecept.overnight.conf.js
  test/e2e/codecept.smoke.conf.js
  test/e2e/helpers/JSWait.js
  test/e2e/helpers/SauceLabsReportingHelper.js
  test/e2e/helpers/idamConfigHelper.js
  test/e2e/helpers/idamHelper.js
  test/e2e/pages/common/end.step.js
  test/e2e/pages/common/error.js
  test/e2e/pages/common/idam.step.js
  test/e2e/pages/progressBar.step.js
  test/e2e/pages/steps.js
  test/functional/helpers/caseHelper.js
  test/functional/helpers/idamHelper.js
  test/functional/paths/pages.js
  test/functional/smoke/smoke.js
  test/resources/basic-divorce-session.json
  test/unit/helpers/caseOrchestrationHelper.test.js
  test/unit/services/caseOrchestrationService.test.js
Labels: ns:div-da-pr-59

#40 DIV-5198: Add decree nisi answers to landing page
  config/default.yml
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petitioner/progress-bar/ProgressBar.content.json
  test/unit/steps/petitioner/progressBar.test.js
Labels: ns:div-da-pr-40
