Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2020-11, with the labels that each got.

#122 TA-53 Functional tests for English and Welsh journeys
  functional-output/Happy_Path.failed.png
  functional-output/Pages.failed.png
  package.json
  test/a11y/index.js
  test/functional/codecept.conf.js
  test/functional/helpers/JSWait.js
  test/functional/pages/accessibilityStatment.step.js
  test/functional/pages/applyForDecreeAbsolute.js
  test/functional/pages/contactDivorceTeamError.js
  test/functional/pages/cookie.step.js
  test/functional/pages/done.step.js
  test/functional/pages/exit.step.js
  test/functional/pages/petitionerProgressBar.js
  test/functional/pages/privacyPolicy.step.js
  test/functional/pages/respondentProgressBar.js
  test/functional/pages/termsAndCondiction.step.js
  test/functional/paths/petitionerPages.js
  test/functional/paths/respondentPages.js
Labels: ns:divorce, prd:div, rel:div-da-pr-122

#125 chore(TA-299): Update crossbrowser config and dependencies
  config/custom-environment-variables.yml
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/functional/codecept.conf.js
  test/functional/helpers/JSWait.js
  test/functional/helpers/SauceLabsReportingHelper.js
  test/functional/helpers/caseConfigHelper.js
  test/functional/helpers/elementExist.js
  test/functional/helpers/idamHelper.js
  test/functional/helpers/urlHelper.js
  test/functional/pages/idam.step.js
  test/functional/paths/petitionerPages.js
  test/functional/paths/respondentPages.js
  test/functional/saucelabs.conf.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-125

#123 Implementing Nightly pipeline
  Jenkinsfile_nightly
  package.json
Labels: ns:divorce, prd:div, rel:div-da-pr-123

#127 Feature(TA-300): Add crossbrowser testing for all browsers
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  package.json
  test/functional/helpers/JSWait.js
  test/functional/helpers/idamHelper.js
  test/functional/pages/applyForDecreeAbsolute.js
  test/functional/pages/done.step.js
  test/functional/pages/idam.step.js
  test/functional/pages/petitionerProgressBar.js
  test/functional/pages/respondentProgressBar.js
Labels: ns:divorce, prd:div, rel:div-da-pr-127
