Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2020-07, with the labels that each got.

#111 RPET-298-app-insights-config
  server.js
  services/setupSecrets.js
Labels: ns:divorce, prd:div, rel:div-da-pr-111

#113 Remove LaunchDarkly and Feature Toggles
  app.js
  config/default.yml
  core/components/launch-darkly.js
  core/utils/featureToggle.js
  middleware/checkWelshToggle.js
  steps/accessibility-statement/AccessibilityStatement.step.js
  steps/contact-divorce-team-error/ContactDivorceTeamError.step.js
  steps/cookies-policy/CookiesPolicy.step.js
  steps/done/Done.step.js
  steps/exit/Exit.step.js
  steps/petitioner/apply-for-da/ApplyForDecreeAbsolute.step.js
  steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.step.js
  steps/petitioner/progress-bar/PetitionerProgressBar.step.js
  steps/privacy-policy/PrivacyPolicy.step.js
  steps/respondent/progress-bar/RespondentProgressBar.step.js
  steps/terms-and-conditions/TermsAndConditions.step.js
  test/unit/core/components/launch-darkly.test.js
  test/unit/core/utils/featureToggle.test.js
  views/includes/phase_banner.html
Labels: ns:divorce, prd:div, rel:div-da-pr-113

#114 Fully remove LaunchDarkly
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  README.md
  charts/div-da/Chart.yaml
  charts/div-da/values.preview.template.yaml
  charts/div-da/values.yaml
  config/custom-environment-variables.yml
  config/default.yml
  config/dev_template.yaml
  infrastructure/main.tf
  package.json
  services/setupSecrets.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-114

#116 remove yarn audit as its now run elsewhere
  Jenkinsfile_CNP
Labels: ns:divorce, prd:div, rel:div-da-pr-116

#115 WLA-590: Enable Language Toggle on UI
  app.js
  config/default.yml
  package.json
  views/includes/phase_banner.html
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-115

#117 bump dependency version and add to resolutions
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-117
