Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2020-10, with the labels that each got.

#120 upgrade AzureRM
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:divorce, prd:div, rel:div-da-pr-120

#119 RPET-361: fix CVE issues
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-119

#121 Pa11y report fix
  package.json
Labels: ns:divorce, prd:div, rel:div-da-pr-121

#118 DIV-6516: Display General order documents
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/mock-case-resp.json
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  steps/petitioner/progress-bar/PetitionerProgressBar.content.json
  steps/respondent/progress-bar/RespondentProgressBar.content.json
  test/unit/steps/petitioner/progressBar.test.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:divorce, prd:div, rel:div-da-pr-118
