Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2020-01, with the labels that each got.

#96 Delete ASE
  Jenkinsfile_CNP
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-da-pr-96

#97 Updating ctsc opening hours
  common/content.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-case-resp.json
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  mocks/services/case-orchestration/submit-da/__/mock-case.json
  steps/accessibility-statement/AccessibilityStatement.content.json
  steps/contact-divorce-team-error/ContactDivorceTeamError.content.json
  steps/exit/Exit.content.json
  steps/petitioner/progress-bar/PetitionerProgressBar.content.json
  steps/respondent/progress-bar/RespondentProgressBar.content.json
  test/unit/resources/courtsList.json
  views/errors/error-content.json
Labels: ns:divorce, rel:div-da-pr-97

#98 Bumped Node to version 12
  .nvmrc
  Dockerfile
  README.md
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:divorce, rel:div-da-pr-98

#99 Code cleanup
  .github/CONTRIBUTING.md
  assets/js/showHideContent.js
  common/steps/progress-bar/ProgressBar.step.js
  mocks/services/case-orchestration/retrieve-aos-case/mock-case-resp.json
  mocks/services/case-orchestration/retrieve-case/mock-case.json
  mocks/services/case-orchestration/submit-da/__/mock-case.json
  mocks/steps/modify-session/ModifySession.html
  steps/respondent/progress-bar/RespondentProgressBar.step.js
  yarn.lock
Labels: ns:divorce, rel:div-da-pr-99
