Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2021-12, with the labels that each got.

#189 Output Redis Info to Log
  README.md
  server.js
Labels: ns:divorce, prd:div, rel:div-da-pr-189

#190 Revert "Output Redis Info to Log"
  README.md
  server.js
Labels: ns:divorce, prd:div, rel:div-da-pr-190

#191 DFR-701: Upgrade redis
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-191

#192 DFR-736: updated fortify release id
  test/java/config/fortify-client.properties
Labels: ns:divorce, prd:div, rel:div-da-pr-192
