Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2021-05, with the labels that each got.

#145 fixed redis sec issue
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-145

#146 PET-981: Fix dependency checks
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-146

#148 RPET-981: updating DA url to fix tests on master
  charts/div-da/Chart.yaml
  charts/div-da/values.yaml
  config/example-local-aat.yml
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-148

#153 RPET-981: Fix dependency errors
  charts/div-da/Chart.yaml
  charts/div-da/values.yaml
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-153

#154 RPET-981: Removing test group code. No longer needed
  test/functional/helpers/idamHelper.js
Labels: ns:divorce, prd:div, rel:div-da-pr-154

#155 RPET0981: Update dependency imports
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-155

#156 RPET-981: Removing recent dependency updates
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-156

#157 It was discussed with TA team that we don't need to run e2e tests for static pages
  test/functional/paths/petitionerPages.js
  test/functional/paths/respondentPages.js
Labels: ns:divorce, prd:div, rel:div-da-pr-157

#158 RPET-1014: Upgrading idam test harness
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-158
