Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2022-05, with the labels that each got.

#241 DFR 979 Fix missing webchat title
  steps/avaya-webchat/AvayaWebchat.html
  views/includes/problem_with_this_page.html
Labels: bug, ns:divorce, prd:div, rel:div-da-pr-241

#245 Increase CPU request
  charts/div-da/Chart.yaml
  charts/div-da/values.yaml
Labels: ns:divorce, prd:div, rel:div-da-pr-245

#246 DFR-1086 Configure Pipelines for Additional Tests
  Jenkinsfile_CNP
  README.md
Labels: ns:divorce, prd:div, rel:div-da-pr-246

#247 DFR-1086 Remove pipeline trigger
  Jenkinsfile_CNP
Labels: ns:divorce, prd:div, rel:div-da-pr-247

#243 Dfr 611 remove feature toggles
  app.js
  charts/div-da/Chart.yaml
  charts/div-da/values.preview.template.yaml
  charts/div-da/values.yaml
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  infrastructure/prod.tfvars
  middleware/helmet.js
  package.json
  test/unit/middleware/helmet.test.js
  test/unit/views/contactus.test.js
  views/includes/problem_with_this_page.html
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-243, enable_all_tests_and_scans
