Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2022-08, with the labels that each got.

#262 Roll back redis update
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-262

#264 SuppressingDependency
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-da-pr-264

#265 pipeline fix
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-da-pr-265

#266 suppress content length limit for file upload
  services/fileManagement.js
Labels: ns:divorce, prd:div, rel:div-da-pr-266

#267 sonarqube suppression
  services/fileManagement.js
  sonar-project.properties
Labels: ns:divorce, prd:div, rel:div-da-pr-267

#268 use sonar properties file to suppress content length limit for file u…
  sonar-project.properties
Labels: ns:divorce, prd:div, rel:div-da-pr-268

#252 DFR-1092 Update Telephone Change of Hours in Guidance
  app.js
  charts/div-da/Chart.yaml
  charts/div-da/values.yaml
  common/content.json
  config/default.yml
  steps/accessibility-statement/AccessibilityStatement.content.json
  steps/accessibility-statement/AccessibilityStatement.html
  steps/contact-divorce-team-error/ContactDivorceTeamError.content.json
  steps/exit/Exit.content.json
  steps/exit/Exit.html
  steps/petitioner/progress-bar/PetitionerProgressBar.content.json
  steps/respondent/progress-bar/RespondentProgressBar.content.json
  test/unit/mock/steps/idamLogin.test.js
  test/unit/steps/common/accessibilityStatement.test.js
  test/unit/steps/common/contactDivorceTeamError.test.js
  test/unit/steps/common/cookiesPolicy.test.js
  test/unit/steps/common/done.test.js
  test/unit/steps/common/exit.test.js
  test/unit/steps/common/privacyPolicy.test.js
  test/unit/steps/common/termsAndConditions.test.js
  test/unit/steps/petitioner/applyForDecreeAbsolute.test.js
  test/unit/steps/petitioner/exitNoLongerWantsToProceed.test.js
  test/unit/views/contactus.test.js
  views/errors/error-content.json
  views/includes/problem_with_this_page.html
  views/includes/sideMenuCourtDetails.html
Labels: ns:divorce, prd:div, enable_all_tests_and_scans, rel:div-da-pr-252

#269 Add backstage configuration file
  catalog-info.yaml
Labels: ns:divorce, prd:div, rel:div-da-pr-269
