Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2022-03, with the labels that each got.

#217 DFR-901 Fix DecreeAbsolute
  package.json
  test/w3cjs/index.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-217

#219 fix vul and bump chart version
  charts/div-da/Chart.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-219

#208 DFR-852 Remove Retention Warning Text from Respondent Template
  steps/respondent/progress-bar/sections/DivorceGranted.html
Labels: ns:divorce, prd:div, rel:div-da-pr-208

#212 Dfr 829 hide respondent docs for single case
  config/default.yml
  steps/respondent/progress-bar/RespondentProgressBar.step.js
  steps/respondent/progress-bar/sections/DivorceGranted.html
Labels: ns:divorce, prd:div, rel:div-da-pr-212

#222 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-da-pr-222

#223 Update progressBar.test.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:divorce, prd:div, rel:div-da-pr-223

#224 Update yarn audit known issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-da-pr-224

#228 Update yarn audit known issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-da-pr-228

#229 Bumping nanoid, minimist
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-229
