Repository hmcts/div-decree-absolute-frontend, pull requests merged in 2022-01, with the labels that each got.

#193 DFR-701: Upgrade One Per Page library
  charts/div-da/Chart.yaml
  charts/div-da/values.preview.template.yaml
  config/custom-environment-variables.yml
  config/default.yml
  package.json
  services/redis.js
  sonar-project.properties
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-193

#161 DFR-37 Deploy Cookie Banner for Dynatrace
  .eslintignore
  README.md
  app.js
  assets/js/cookiesManager.js
  assets/js/main.js
  assets/scss/_cookies.scss
  charts/div-da/Chart.yaml
  charts/div-da/values.preview.template.yaml
  charts/div-da/values.yaml
  config/custom-environment-variables.yml
  config/default.yml
  steps/cookies-policy/CookiesPolicy.content.json
  steps/cookies-policy/CookiesPolicy.html
  views/errors/not-found-error.html
  views/errors/server-error.html
  views/includes/cookies/button/macro.njk
  views/includes/cookies/button/template.njk
  views/includes/cookies/cookie-banner/cookie.njk
  views/includes/cookies/cookie-banner/macro.njk
  views/includes/cookies/cookie-banner/template.njk
  views/includes/cookies/cookie-manager/cookie-banner.njk
  views/includes/cookies/cookie-manager/cookie-reject-all-banner.njk
  views/includes/cookies/cookie-manager/cookie-success-all-banner.njk
  views/includes/cookies/cookie-manager/cookie-success-banner.njk
  views/includes/head.html
  views/page.njk
  views/question.njk
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-da-pr-161

#199 DFR-37-Webchat-Fix
  assets/js/cookiesManager.js
Labels: ns:divorce, prd:div, rel:div-da-pr-199

#201 Resolve header manipulation fortify errors
  assets/js/cookiesManager.js
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-da-pr-201

#202 Update server.js
  server.js
Labels: ns:divorce, prd:div, rel:div-da-pr-202
